-- EXISTS 사용
# SELECT DISTINCT c1.CART_ID
# FROM CART_PRODUCTS c1
# WHERE c1.NAME = 'Milk'
#     AND EXISTS(
#         SELECT 1
#         FROM CART_PRODUCTS c2
#         WHERE c1.CART_ID = c2.CART_ID
#             AND c2.NAME = 'yogurt'
#     )
# ORDER BY c1.CART_ID;

-- SELF JOIN 사용
SELECT DISTINCT c1.CART_ID
FROM CART_PRODUCTS c1
JOIN CART_PRODUCTS c2
    ON c1.CART_ID = c2.CART_ID
WHERE c1.NAME = 'Milk'
    AND c2.NAME = 'Yogurt'
ORDER BY c1.CART_ID;

-- IN, GROUP BY + HAVING 사용
SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME IN ('Milk', 'Yogurt')
GROUP BY CART_ID
HAVING COUNT(DISTINCT NAME) = 2
ORDER BY CART_ID;